# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://shengbaishu.com'
baseurl: ''
title: 'ShengBaiShu.com'
description: '圣白树专注正版模玩'
permalink: pretty
logo: "https://img.alicdn.com/imgextra/i3/2710706468/O1CN01MSs8GS1xeOV16mYim_!!2710706468.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: 首页
  url: /
- title: 关于
  url: /about/
- title: 联系
  url: /contact/
- title: 动态
  url: /blog/

# Footer nav
navigation_footer:
- title: 返回顶部↑Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: 近期动态
    output: true
    description: "请联系我们的QQ：2669505"
    feature_text: 
    feature_image: 

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
