# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://daijianpu.com'
baseurl: 'https://www.daijianpu.com'
title: 'Daijianpu.COM'
description: 'mail@daijianpu.com'
permalink: pretty
logo: "https://img.alicdn.com/imgextra/i3/2710706468/O1CN01MSs8GS1xeOV16mYim_!!2710706468.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Domain
  url: /domain/
- title: Contact
  url: /contact/
- title: About
  url: /about/
  
# Footer nav
navigation_footer:
- title: Back t↑o top
  url: "#top"

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "mail@daijianpu.com"
    feature_text: 
    feature_image: https://img.alicdn.com/imgextra/i4/2710706468/O1CN01RGST211xeOUvUE6ua_!!2710706468.jpg

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
