# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://shengbaishu.com'
baseurl: ''
title: '圣白树'
description: '圣白树专注正版模玩供应链批发零售代销分销假面骑士奥特曼周边玩具模型'
permalink: pretty
logo: "https://img.alicdn.com/imgextra/i3/2710706468/O1CN01MSs8GS1xeOV16mYim_!!2710706468.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: 首页
  url: /
- title: 关于
  url: /about/
- title: 联系
  url: /contact/
- title: 资讯
  url: /info/

# Footer nav
navigation_footer:
- title: 返回顶部↑Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: 近期动态
    output: true
    description: "请联系我们的QQ：2669505"
    feature_text: 
    feature_image: https://img.alicdn.com/imgextra/i4/2710706468/O1CN01RGST211xeOUvUE6ua_!!2710706468.jpg

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
